### ISSUE TITLE
Document the process of creating a custom field.

### ISSUE THREAD

**Issue by AnmAtAnm** [google/blockly#1623]
As of #1594, custom fields are now possible without modifying the core blockly code.

## Audit field APIs

Improve the `Field` class APIs to a level we are willing to support long term.

 * [ ] Use setText instead of setValue in fieldTextInput (#860).
 * [ ] Extract common Field support methods into new field_util.js (#1624).
 * [ ] Consistently call Field.init() from subclass .init() (or refactor to put ensure it is called in other ways).
 * [ ] Split `Field.init()` into `Field.initView()` and `Field.initModel()` (#1010). 
 * [ ] Consider splitting Field view and model more completely. For instance, `updateWidth()` is another view specific method.
 * [ ] Validation: Do we validate the text of the field, the value, or both (need separate APIs)?

## Document custom field development process and concerns

Write the documentation for the following aspects of the improved API.

 * [ ] Field class hierarchy, denoting where good extension points are.
 * [ ] Document required Field methods and life cycle of a Field object.
 * [ ] Difference between setText() vs setValue().
 * [ ] Timeline and expectations between `showEditor()` and registering event listeners and `hideChaff()`.
 * [ ] How to attach popup editors to a field.
 * [ ] Document the registration functions.

**Comment by BeksOmega** [comment]
Would you peoples mind if I took a look at refactoring some of the field API stuffs?

If you don't I'll work up a little class diagram that you can look at before I get started. If you don't want me to touch it that's cool too =)

**Comment by RoboErikG** [comment]
If you want to tackle some of the concrete issues or build out some more detail on others feel free.

I don't think we've fully discussed everything on this list, so there may be some suggestions and back and forth before you get the go ahead to implement some of them. =)

Also, Rachel is out this week and should have final say on any big changes.

**Comment by BeksOmega** [comment]
So I read through a bunch of the field files and came up with a [WIP class diagram](https://www.lucidchart.com/invitations/accept/b049efd6-c5fe-49d6-a484-e6708a52f6a6). It has the main abstract field class and then three other concrete classes that I worked up to test if the abstract class made sense. The properties of the abstract field class that are blue are the ones I think should be optionally overriden by subclasses.

There are a couple things to note:
- This adds an isDirty_ property to the field so that [getSize ](https://github.com/google/blockly/blob/82871b3d24563388a6f113da8984694e9f37b53e/core/field.js#L454)can use that instead of checking if the width has been set to zero.
- This adds a serializable property to the field in addition to the current editable property. I ran into the serializable/editable problem when developing my application, and I saw that scratch had added this functionality as well, so I thought it might be nice to port to the core.

And there are a couple things I'm still unsure about:
- What was the purpose of setText vs setValue and is setText still necessary? I think it makes sense that if not all fields have text, the abstract field class shouldn't have text-specific functionality. But I don't know the history behind having both so I'm not sure.
- How should initView / DOM inheritance work? I don't think that the abstract field class should create elements like borderRect_ and textElement_ when fields like field_label and field_checkbox don't use them. But then it brings up the question of if all bordered fields should subclass from some field_border class or if they should each create their borderRect_ individually.

Do you have any recommendations on how to proceed?

**Comment by RoboErikG** [comment]
Whoah, thanks for doing such a deep dive, Beka!

Here are my initial comments, but you should wait for Rachel's feedback next week.

- Overall the structure looks good.
- Is dirty is a good idea and we may make use of it some day to optimize the render compute path.
- Be careful with isDirty_ and serializable, developers will need to make changes if they added any fields so you'll need to be thoughtful about the defaults and how to fallback if the developer doesn't update their custom fields.

**setText vs setValue**

Think of setText as setDisplayText. That's what should be rendered on the block if it renders as text or could be used by Screen Readers to describe the current value (images also have alt text). The value is the internal representation of what is set for that field. The clearest example is in a dropdown where you set both explicitly. Historically, these were not kept cleanly distinct so there are some fields where they are the same thing. 

I think the majority of fields will benefit from a user readable string, so I'd be inclined to keep setText on the base class.

**initView / DOM**

You may have to wait for Rachel on this one. She's been working through a rendering redesign and I'm not sure how she wants fields to be handled.

**Comment by BeksOmega** [comment]
So about backwards compatability, what are your general rules for maintaining it? For example how would you handle splitting init() into initModel() and initView()? I want to make sure I follow the same proceedure you peoples would.

**Comment by RoboErikG** [comment]
We generally make a best effort to maintain backwards compatibility and log warning messages if we have to change something and it's easy to detect the old thing is being used.

For splitting init into initModel and initView you probably want to keep init and just have it call both initModel and initView.

A separate step will be figuring out where to call initModel from when in headless mode.

**Comment by BeksOmega** [comment]
Hello, I was just wondering if there were any updates on this, or if it should wait until the rendering redesign has more time to proof.

**Comment by rachel-fenichel** [comment]
Hey Beka,

I'm back from vacation but jumped into two days of meetings (>.<) so I haven't gotten to look at this yet.  Sorry for the delay.

If you want to look at the rendering rewrite to get a sense of what I'm doing structurally, the files are up on my github: https://github.com/rachel-fenichel/blockly/tree/render_rewrite/core/block_rendering_rewrite

**Comment by BeksOmega** [comment]
>I'm back from vacation but jumped into two days of meetings (>.<)

That should be illegal! Like tests on mondays D:
 
> If you want to look at the rendering rewrite to get a sense of what I'm doing structurally, the files are up on my github.

Eeek yes! Please and thank you =) It looks beautiful!

**Comment by rachel-fenichel** [comment]
Screenshot of Beka's diagram: 
![image](https://user-images.githubusercontent.com/13686399/55996412-3102c800-5c6c-11e9-89c2-136c0f869d57.png)

Questions:
- Symbols you're using: + is public, - is private, ~is protected?
- What are the blue functions?
- What are `getCursor` and `setCursor`?
- What does `isCurrentlyVisible` check?

Comments:
- Definitely port `serializable` back from scratch-blocks.  That's probably a good one to do as a standalone PR.
- `isDirty` is a good idea.  Using whether the width has been set has led to some unnecessarily complicated code.
  - I think this would also be good to do as a standalone PR.
- Please liberally add test blocks to the playground as you work on this, if you get into any weird cases.
- Possibly also add a `type` string and `getType` function.
> How should initView / DOM inheritance work? I don't think that the abstract field class should create elements like borderRect_ and textElement_ when fields like field_label and field_checkbox don't use them. But then it brings up the question of if all bordered fields should subclass from some field_border class or if they should each create their borderRect_ individually.

- This one will have to come after my rendering rewrite.  Currently the size of the border rect and text element get used for figuring out the size of the field for doing layout, often in non-obvious ways.  In my rewrite I added a function, `getCorrectedSize`, that should figure out the visible size of the field for rendering.  I added it as a separate function instead of changing `getSize` so that my changes don't impact the old renderer, but once it's in I was planning to go field-by-field to try to clarify how the size of the border rect and text element are used.

**Comment by rachel-fenichel** [comment]
Oh whoops, you answered one of my questions:
> The properties of the abstract field class that are blue are the ones I think should be optionally overriden by subclasses.

**Comment by BeksOmega** [comment]
> Symbols you're using: + is public, - is private, ~is protected?

\+ is public
\- is private
~ is protected: "Should not be called by dev code, only package code, but can be overriden by dev classes." I found the JSDoc doc definition of protected confusing, so I just went with the Java/C# definition.

> What are getCursor and setCursor?

These are accessors to set/get what the mouse cursor will be when it hovers over the field.

> What does isCurrentlyVisible check?

Typo, should have been [isVisible](https://github.com/google/blockly/blob/82871b3d24563388a6f113da8984694e9f37b53e/core/field.js#L268).

**setText vs setValue**
My thoughts with regard to setText vs setValue are that it seems like a great idea to give every field a textElement_, there by "enforcing" (or at least strongly suggesting :P) screen reader support, but I also think it might be confusing to allow it to be set externally. For example with the dropdown @RoboErikG mentioned you can put it in a situation like this:

![SetTextExample](https://user-images.githubusercontent.com/25440652/55633801-fa134a80-5771-11e9-8990-8057a09d8e51.jpg)

Where the dropdown can display one option, but a different one is actually selected.

I don't think this occures often since I think most people will call block.setFieldValue('new language neutral value', 'NAME') rather than block.getField('NAME').setText('new language explicit value'). But I think it's confusing to allow it anyway. If the only access point was setValue a state like the above would be impossible.

**Private vars vs Constants**
Before I go implimenting the serializable support I would like to clarify whether it should be made a constant like scratch-blocks implimented it, or whether it should be made a private variable with setters and getters.

In my diagram I implimented it as the latter, because it seems like it will be more intuitive for developers to call a setSerializable function on a specific field rather than creating a new class, and because I think people may end up overriding it anyway (e.g. [this gentle person](https://groups.google.com/forum/#!searchin/blockly/EDITABLE/blockly/rzcpN8iIrRU/Z6_5XZ1pBgAJ), and [myself](https://github.com/BeksOmega/blockly/blob/54908ebba4b3893e594095c93294b3ee06bb3a40/blocks/pieces.js#L8)) even if it is declared as a constant.

On the other hand whichever way we decide to go I think the serializable property and the editable property should match (that is they should either both be constants or both be private vars). And keeping editable a constant seems like a good way to maintain backwards compatability.

**Field Sizing w/ New Rendering**
I'm not as familiar with the rendering code as @rachel-fenichel  is, but my first thought was to have getSize() return based on the size of the fieldGroup_. Stuff would probably have to be shuffled around, and field classes would probably still be doing some "interesting" border resizing based on text and things, but at least developer & renderer code could trust that getSize() returned the correct visible size. And maybe it could even be set up in such a way that new fields wouldn't need to override getSize().

**Comment by rachel-fenichel** [comment]
SetText vs setValue: both of them currently exist, so we're going to keep supporting them, even if we suggest that most people use `setValue`.  As far as I know, calling `setText` should also update the value of the field, cause rerenders, etc.

**Private vars vs Constants**
Let's go with a constant (per field type) the way it is for scratch-blocks.  This lets it match editable, and also avoids having serializable state change at runtime.

**Comment by rachel-fenichel** [comment]
Thanks for handling the serializable changes!

I have a project proposal for you, if you're interested.  It's a way for us to get documentation (at least a first draft) and a demo, and for you to build something with turtles.  

As always, no pressure if you choose not to do this.

### Problem statement
- Customizing turtles is hard.  
- We have no documentation for how to build a custom field.

### Proposed solution
- Build a turtle-customization field.
- Make a page in the `demos` folder that uses the field in a basic way--just a workspace with that field on a block--to show off editing, loading, and saving.
- Write down the steps you take, in a doc and (if you want) in comments in your demo code.
- We take your write-up, tweak it, and make a page for it on the developer site.

### Field specification
- The field displays a turtle on the block (as an svg image, probably)
- The turtle has a name, a hat, and a shell color or pattern
- Clicking on the turtle opens an editor widget
- The editor widget has three buttons:
  - Change hat
  - Change shell
  - Change name
- Clicking a button randomly selects a new (hat, shell, name) and updates the turtle on the block (or a preview, if you want the widget to cover the field entirely)
- Saving to XML saves the name, hat, and shell color.  Loading loads those in.

### UI mock-ups
Field used on a block:
![image](https://user-images.githubusercontent.com/13686399/56686591-28a58680-6689-11e9-9181-9716c128e928.png)

Field with editor open:
![image](https://user-images.githubusercontent.com/13686399/56686610-33f8b200-6689-11e9-9725-ac88537d4667.png)

Field with editor closed after randomly setting shell color and name:
![image](https://user-images.githubusercontent.com/13686399/56686953-06f8cf00-668a-11e9-9053-05e5e8519bb6.png)

### Documentation specification
- Steps you took to make the new field
- Files you had to change, if any
- APIs you had to implement (e.g. `render`, `init`)
- Anything else you think a fellow developer would want to know

**Comment by BeksOmega** [comment]
> I have a project proposal for you, if you're interested. It's a way for us to get documentation (at least a first draft) and a demo, and for you to build something with turtles.

This sounds super fun! I'd love to give it a shot!

> ### Proposed solution
> * Build a turtle-customization field.
> * Make a page in the `demos` folder that uses the field in a basic way--just a workspace with that field on a block--to show off editing, loading, and saving.
> * Write down the steps you take, in a doc and (if you want) in comments in your demo code.
> * We take your write-up, tweak it, and make a page for it on the developer site.

Loading and saving like the same way the playground does?

> ### Field specification
> * The field displays a turtle on the block (as an svg image, probably)
> * The turtle has a name, a hat, and a shell color or pattern
> * Clicking on the turtle opens an editor widget
> * The editor widget has three buttons:
>   
>   * Change hat
>   * Change shell
>   * Change name
> * Clicking a button randomly selects a new (hat, shell, name) and updates the turtle on the block (or a preview, if you want the widget to cover the field entirely)
> * Saving to XML saves the name, hat, and shell color.  Loading loads those in.

### Suggestions:
* Shell button updates the pattern (as suggested above), and the colour updates with block colour.
* Field has a custom tooltip (and overrides setTooltip) that lists its hat, shell, colour, and name.

> ### Documentation specification
> * Steps you took to make the new field
> * Files you had to change, if any
> * APIs you had to implement (e.g. `render`, `init`)
> * Anything else you think a fellow developer would want to know

Sounds perfect!

I have a few changes that I want to get in before I do this:
A) removing setVisible from the public API #2381 (just want to clean it up before I forget)
B) fromXML and toXML #1627 (this one is almost ready to go)
C) Adding an updateColour function to field.js (This may need to be discussed but it should work similarly to the[ icon updateColour](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/core/icon.js#L138) function and will allow [this ](https://github.com/google/blockly/blob/3342a375ff0cee0be42062765d24922be2917170/core/icon.js#L138)block of code to be changed)

After that I think making a custom turtle field should be a breeze! Thanks for the great suggestion I'm super stoked about it :D

**Comment by rachel-fenichel** [comment]
> Loading and saving like the same way the playground does?

Yup, just a simple textarea with load and save buttons.  Enough for you to demo that code path.

>Suggestions:
Shell button updates the pattern (as suggested above), and the colour updates with block colour.
Field has a custom tooltip (and overrides setTooltip) that lists its hat, shell, colour, and name.

Sounds good.

**Comment by BeksOmega** [comment]
Wanted to give you guys an update on my current progress!

#### General Fields Documentation:
* Overview info
* Validators info
* New docs for each field type.

The writing is completed! But I'd like to give it a proof read before I send it in, and it needs images and GIFs.


#### Creating Custom Fields Documentation:
* Extension Points
* Constructors
* Initialization
* Value Handling
* etc...

Everything except rendering and disposing info has been written. It also needs a few pictures.

#### Must Do
[Fix Disposal](https://github.com/LLK/scratch-blocks/issues/1947): Just needs a reply from the scratch team before I jump in.
[Fix Rendering](https://github.com/google/blockly/issues/2530): This one is going to be a bit trickier, as it touches the current rendering refactor.

#### Best to Do Before Docs (if you want them done)
[Break Field_Utils into Seperate File](https://github.com/google/blockly/issues/1624)
[Create a Render Solution for Statically Sized Fields](https://github.com/google/blockly/issues/2490)
[Change how Default Values are Handled](https://github.com/google/blockly/issues/2462#issuecomment-495805195)
[Figure out Fields that Reference Variables](https://github.com/google/blockly/issues/2531)

Everything else should be pretty easy to do piecemeal!
#### Conclusion
I don't need replies to anything immediately, I just wanted to give you guys an idea of how everything has been progressing and what still needs doing. Thank you so much for letting me work on this! It's been super fun =D

**Comment by BeksOmega** [comment]
Ok I have completed a [field documentation prototype](https://docs.google.com/document/d/1ONGGy0A_w24L2fDH5AqI5yQG1iyl91hEbAjMiRf3268/edit?usp=sharing).

I tried my best to follow the [Write the Docs Documentation Principles](http://www.writethedocs.org/guide/writing/docs-principles/), as well as the [Google Documentation Style Guide](https://developers.google.com/style/) as I was writing.

I have given edit access to Abby, Andrew, Erik, Neil, and Rachel (or tried to anyway). Please tell me if anyone needs to be added or removed.

I have also shared a link with comment access [on the forums](https://groups.google.com/forum/#!topic/blockly/kWZDQD7-A9w), because I thought it would be a good way to get outside developers' opinions on the changes.

**Comment by RoboErikG** [comment]
This is awesome, Beka. Just an FYI, we're all going to be at a larger team offsite this week so reviews may be a bit slow.

**Comment by rachel-fenichel** [comment]
All right, let's figure out how we're going to structure this on the developers site.  We can do editing in parallel, and once we're done editing one (or all) of Blockly team will port the code over to the developers site.

Proposed structure:
- Create Custom Blocks
  - Overview
  - Blockly Developer Tools
  - Define Blocks
  - Fields
    - Overview
    - Built-in fields
    - Custom fields
      - Extending a built-in field
      - Creating a custom field
      - Upgrading a custom field

The **Overview** page will include, in order:
- Anatomy of a field
- Field APIs
- Validators
- Customizing fields (which corresponds to your **custom fields** section)

The **Built-in fields** page will be a single page, similar in structure to the **fields** section of the **Define Blocks** page, but with all of your new details.  That corresponds to pages 33-67 (ish) of your doc, which describe field types that we provide in the core library. 
Most field types have:
- Creation 
  - Explanation/description
  - JSON and JavaScript code snippets
- Serialization and XML
  - Explanation/description
  - XML code snippet
- Customization
  - Details vary by field type
- Creating a <field type> validator

A few have other things--number fields list common constraints, image fields describe click handling, etc.

The **Extending a built-in field** page will include your section on **Extension points**, with all of the associated links that you have in it.  That page may be short and sweet.

The **Creating a custom field** page will correspond to your **Creating a new field type**, and **Upgrading a custom field** will correspond to your **Upgrading a custom field** section.

**Comment by BeksOmega** [comment]
No opinions on structure, I figure you guys know that better than I do.

I do I want to clarify that I think code snippets should be included before explanation/description. I think this makes the documentation more [exemplary ](http://www.writethedocs.org/guide/writing/docs-principles/#exemplary)and more [skimmable](http://www.writethedocs.org/guide/writing/docs-principles/#skimmable).

New **Extending a built-in field** page is noted.

I also wanted to mention [this](https://docs.google.com/document/d/1ONGGy0A_w24L2fDH5AqI5yQG1iyl91hEbAjMiRf3268/edit?disco=AAAADKgckSo) comment: 

> Could GIFs and Images instead be readonly workspaces? as referenced [here]( https://developers.google.com/blockly/guides/create-custom-blocks/style-guide#4_live_block_images). I think this could be very useful as the [old field images](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#colour_picker_field) have gone out of date. I would definitely be willing to write the code for them.

**Comment by rachel-fenichel** [comment]
I agree that it would be a good idea to have readonly workspaces for the gifs and images, but for the sake of getting this published before our next release, let's just do gifs and images for now, and circle back after the release.

**Comment by BeksOmega** [comment]
Sounds good, then I need to know:
* Image dimensions.
* Image formats.
* Gif dimensions.
* Max file sizes.

Or if it doesn't matter then I need to know that as well.

**Comment by rachel-fenichel** [comment]
It looks like we mostly use PNGs for images.  MP4 for gifs, unless someone says otherwise.  I don't think we have a file size limit.  In general, whatever we're already doing on devsite is good.

**Comment by Chappie74** [comment]
> Ok I have completed a [field documentation prototype](https://docs.google.com/document/d/1ONGGy0A_w24L2fDH5AqI5yQG1iyl91hEbAjMiRf3268/edit?usp=sharing).
> 
> I tried my best to follow the [Write the Docs Documentation Principles](http://www.writethedocs.org/guide/writing/docs-principles/), as well as the [Google Documentation Style Guide](https://developers.google.com/style/) as I was writing.
> 
> I have given edit access to Abby, Andrew, Erik, Neil, and Rachel (or tried to anyway). Please tell me if anyone needs to be added or removed.
> 
> I have also shared a link with comment access [on the forums](https://groups.google.com/forum/#!topic/blockly/kWZDQD7-A9w), because I thought it would be a good way to get outside developers' opinions on the changes.

Thanks for this wonderful piece of document. I find this much more informative than the Blockly documentation. <3

**Comment by BeksOmega** [comment]
> Thanks for this wonderful piece of document. I find this much more informative than the Blockly documentation. <3

Haha I'm glad you like it! It's funny because the team actually used that doc to create the documentation that lives on the dev site. i'd love to know what you like about the google doc so that it could be added to the devsite (if possible).

**Comment by Chappie74** [comment]
> > Thanks for this wonderful piece of document. I find this much more informative than the Blockly documentation. <3
> 
> Haha I'm glad you like it! It's funny because the team actually used that doc to create the documentation that lives on the dev site. i'd love to know what you like about the google doc so that it could be added to the devsite (if possible).

I actually didn't realise that it was there under the  *Guides* section of the official docs. I was more so comparing it to the *Reference* section lol. I read the google docs in full and that helped me get a better understanding nevertheless.

**Comment by BeksOmega** [comment]
> I actually didn't realise that it was there under the _Guides_ section of the official docs. I was more so comparing it to the _Reference_ section lol. I read the google docs in full and that helped me get a better understanding nevertheless.

Yay I'm glad you found it useful!

> Also, if its okay with you, may I contact you for further assistance?

Sure thing! The best way to reach me is through the [forums](https://groups.google.com/g/blockly). If you post there I'll see it, I check it every day =) Plus someone else might have tips for you as well!
