### ISSUE TITLE
Node.js Tracking bug

### ISSUE THREAD

**Issue by NeilFraser** [google/blockly#2082]
Meta bug for tracking issues with running Blockly under Node.js.

Known issues:
- [ ] `Blockly.utils.xml.createElement` & `Blockly.utils.xml.createTextNode`
- [ ] `Blockly.utils.xml.domToText`
- [x] `Blockly.utils.xml.textToDomDocument`

The initial goal is to be able to load a set of blocks from XML onto a headless workspace, and generate code.

**Comment by AnmAtAnm** [comment]
Are you testing these with the Node package created via `gulp build`?

**Comment by NeilFraser** [comment]
I'm not testing this or owning this effort.  Rachel made me file something here so that I could annotate the TODOs in Blockly.Xml.utils that point out the code there fails due to the use of global objects not present in Node (such as document).  :)

**Comment by rachel-fenichel** [comment]
@riknoll Before the holidays I said I'd ping you about remaining steps for Blockly to work under Node.  Here's the tracking bug.  It looks like the number of remaining globals is fairly small.  @AnmAtAnm may have more comments on whether anything else needs to be done.

**Comment by staylornc** [comment]
@rachel-fenichel, is there an update on this issue? We would love to use Blockly within the adaptive learning environments we are creating in Unity, getting this to work would be a huge help to us. Thanks. :-)

**Comment by amber-cd** [comment]
I would also like to ask for an update on this, for the reason that we've actually been using Blockly on Nodejs for some time by doing overrides of the blockToDom and domToVariables to use childNodes instead of children and commenting out `container.appendChild(Blockly.Xml.cloneShadow_(shadow));` in blockToDom. I wouldn't be averse to trying to integrate our Nodejs-only overrides into something that will just behave fine both in the supported browsers and in Nodejs, but all we really do is load saved XML up into non-SVG workspaces in order to regenerate their JavaScript. What all else is known to be an issue when running in Nodejs? Is there a good comprehensive replication of the issues available somewhere? (Of note is that we use xmldom in order to make this work, and I'm not sure if that would be acceptable in the final product either.)

**Comment by rachel-fenichel** [comment]
@amber-cd We don't have anyone actively working on it right now.  Our eng team is focusing on rendering and keyboard navigation.  

I would be open to a PR that gets this working for headless mode (your use case), even if it doesn't fix everything.  

I know that our gulpfile has a snippet of code to use JSDOM instead of DOMParser in Blockly.Xml.utils.textToDomDocument; I think we need to do something similar for the other functions mentioned above.

The other problem I'm aware of is that we have a lot of references to `document`.

**Comment by RoboErikG** [comment]
@samelhusseini can this bug be closed or is there more work to do?

**Comment by samelhusseini** [comment]
Yes, we still need an XML serializer polyfill for ``Blockly.utils.xml.domToText``.
I think we can use ``jsdom`` for that.
``Blockly.utils.xml.createElement`` and ``Blockly.utils.xml.createTextNode`` are taken care of by using ``jsdom`` to polyfill a ``document`` element.
If ``jsdom`` doesn't do it, we should consider just relying on https://www.npmjs.com/package/dom-parser and https://www.npmjs.com/package/xmlserializer for dom parsing and xml serialization.

**Comment by samelhusseini** [comment]
I think this can be closed now.
