### ISSUE TITLE
Cleanup warnings and errors logged in mocha tests

### ISSUE THREAD

**Issue by moniika** [google/blockly#4194]
Mocha tests trigger a variety of warnings and errors.
These warnings and errors logs are caused by a variety of things:
- expected warnings (like deprecation warnings)
- missing cleanup in tests or improper setup of objects used in tests
- bugs that should be filed

We should cleanup the tests so it is easier to use the console when debugging mocha tests and so that any warnings or errors we see in the console when running mocha tests are more meaningful.

**Comment by moniika** [comment]
Remaining logs/warnings triggered by tests:
- [ ] `Comment.prototype.getText` deprecation warning - #4186
- [ ] `Field.prototype.classValidator` deprecation warning - #4197
- [ ] Not expected to reach Block.bumpNeighbours function. BlockSvg.bumpNeighbours was expected to be called instead. - from `logic_ternary_test.js` triggered because test runs on headless.
- [ ] Saw an existing group while responding to a definition change - `from procedures_test.js`

**Comment by moniika** [comment]
- [ ] More recent regression for generator mocha tests emitting warning during `blockToCode` suite is tracked in https://github.com/google/blockly/issues/5029

**Comment by moniika** [comment]
Closing this bug and tracking warning triggered by procedures in https://github.com/google/blockly/issues/5530
