### ISSUE TITLE
Review contents of `blockly.js`

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#5208]
`blockly.js` is full of public stuff that doesn't really fit on any namespace. This is a problem because internal code requiring it causes circular dependencies.

The fix is to move everything in `blockly.js` out into separate files and require those from inside the codebase, while leaving aliases behind in `blockly.js` for anything that should stay publicly accessible.

In some cases, we also need setters so that external code can change those values.

In other cases, properties should just not be exported.

This issue is for tracking decisions about these properties and whether those decisions have been implemented.

Needs decision:
- [ ] `svgResize`
- [ ] `onKeyDown`
- [ ] `deleteBlock`
- [ ] `onContextMenu_`
- [x] `hideChaff`
- [x] `alert`
- [x] `confirm`
- [x] `prompt`
- [x] `hueToHex`

Can be internal:
- [ ] `Blockly.jsonInitFactory_`
- [x] `clipboardXml_` -> `clipboard.js` in #5237
- [x] `clipboardSource_` -> `clipboard.js` in #5237
- [x] `clipboardTypeCounts_` -> `clipboard.js` in #5237
- [x] `parentContainer` -> `common.js` in #5262
- [x] `draggingConnections` -> `common.js` in #5262

Exported function, but moved to a different file and aliased.
- [x] `bindEvent_` -> `Blockly.browserEvents.bind` in #4642 (2021Q1)
- [x] `getMainWorkspace` -> `Blockly.common.getMainWorkspace` in #5244
- [x] `copy` -> `Blockly.clipboard.copy` in #5237, and tracking remaining work in https://github.com/google/blockly-samples/issues/833
- [x] `paste -> `Blockly.clipboard.paste` in #5237, and tracking remaining work in https://github.com/google/blockly-samples/issues/833
- [x] `duplicate` -> `Blockly.clipboard.duplicate` in #5237, and tracking remaining work in https://github.com/google/blockly-samples/issues/833
- [x] `setParentContainer` -> `Blockly.common.setParentContainer` in #5262
- [x] `hueToHex` -> `Blockly.utils.colour.hueToHex` in #5462
- [x] `alert` -> `Blockly.dialog.alert` in #5457 
- [x] `confirm` -> `Blockly.dialog.confirm` in #5457 
- [x] `prompt` -> `Blockly.dialog.prompt` in #5457

Exported function, used only externally and therefore left in `blockly.js`:
- [ ] `isNumber`: Used in generators
- [ ] `defineBlocksWithJsonArray`: Used in block definitions
- [ ] `svgSize`: Deprecated already, and marked for removal in March 2022
- [ ] `resizeSvgContents`

Exported read-only property:
- [ ]

Exported settable property:
- [x] `mainWorkspace` in #5244, with a follow-up to add deprecation warnings.

Can be removed:
- [x] `checkBlockColourConstants`: Only used internally, and as a deprecation helper for an old deprecation. Deleted in #5262.
- [x] `checkBlockColourConstant_`: Only used by `checkBlockColourConstants. Deleted in #5262.
- [x] `cache3dSupported_`: Not used. Deleted in #5262.

**Comment by rachel-fenichel** [comment]
@cpcallen This is obviously incomplete, but is a place to start in on pulling apart `blockly.js`. I think this is going to take multiple passes. For each thing we need to decide what category it belongs in and where to move it to, possibly including creating new files.

**Comment by rachel-fenichel** [comment]
Remaining work:

- [ ] Move `alert`, `confirm`, and `prompt` to a new file
  - [ ] Move functions
  - [ ] Update all internal uses
  - [ ] Add getters and setters in `blockly.js` for backwards compatibility
  - [ ] Record rename in renames file
- [ ] Move `hideChaff` to a new file
  - [ ] Move function and resolve any circular dependencies
  - [ ] Update all internal references
  - [ ] Record rename in renames file
