### ISSUE TITLE
Update Blockly codebase to Typescript

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#5857]
Steps for this update. These are not necessarily in order, and some will be broken out as separate bugs.

Old Tracking List:
- [x] Add a `tsconfig.json`. (#5892)
- [x] Wire the typescript compiler to output into the build directory such that the closure compiler picks up the correct files. (#5892)
- [x] Add gulp tasks and scripts in `package.json` to run the ts compiler and then the closure compiler. (#5892)
- [x] Add gulp tasks and scripts in `package.json` to clean up generated files when needed. (#5892)
- [x] #5904
- [x] #5960

Must happen pre merge:
- [x] Check all `@enums` for formatting issues. [beka]
  - [x] Fix `KeyCodes` in `core/utils/keycodes.ts`. [christopher]
- [x]  Check all `@typedef`s for lost JSDocs. [beka]
- [x] Export `@typedef`s that were static properties on classes [beka]
- [x] Move comments that migrants put in the wrong place [beka]
- [x] Remove remaining `declareLegacyNamespace` calls [christopher]
- [x] Migrate `blockly.js` to `blockly.ts` [christopher]
- [x] Get Blockly to pass CI. [TBD]

Can happen post merge:
- [x] Fix any `@protected` properties that have been changed to parameter properties [beka] 
- [x] Check that public parameter properties are correct [beka]
- [x] Investigate why `compose` is commented out in BlockSvg [beka]
- [ ] ~~Export interface types that were exported from `blockly.js` [beka]~~
- [X] Redefine properties that were defined using `Object.defineProperties` [christopher]
  - [X] Check that we've properly deprecated all of the above properties, including any in blocks or generators. [beka]
- [X] Find new places to put the properties that were defined using `Object.defineProperties` [beka]
- [X] Implement piping sourcemaps from tsc to closure compiler [christopher]
- [X] Get generating type defs working [beka]
  - [X] Rename instances of `AnyDuringMigration` in defs to `any`[beka]
- [X] Fix packaging sources (.ts instead of .js) [beka]
- [X] Get API Extractor Working
  - [x] Get Maribeth set up with a branch that builds [beka]
  - [X] Enable API Extractor. [maribeth]
  - [X] Migrate JSDoc to TSDoc. [TBD]
    - [ ] Move any docs attached to property assignments to property definitions [TBD]
  - [X] Figure out how to pipe the results of API Extractor to devsite [maribeth]
- [ ] Update [the Blockly style guide](https://developers.google.com/blockly/guides/contribute/core/style_guide) to document where we differ from the Google TS (or JS) styleguide
  - E.g., using TSDoc, requiring blank line before `@param`s, listing all `@param`s even when annotation adds no information, etc.
- [X] Update the renamings script to handle the new import structure for blocks and generators [beka]
- [X] Fix BlocklyOptions (which stopped actually defining anything [during the goog.module migration](https://github.com/google/blockly/pull/5287/files)) [beka]
- [x] Make `block.workspace` not nullable [aaron]
- [x] Add type information to interfaces [aaron]

Optional niceties:
- [ ] ~Deal with `IRegistrableField` trying to include a static property in an interface~ We were actually doing this correctly.
- [ ] Remove unused JSDoc attributes
- [X] Get ESLint to work with Typescript [maribeth]
- [X] Fix CSS formatting. E.g. common/constants [beka]
- [X] Look into DynamicShape in common/constants [beka]
- [ ] Update everything to conform to the ts styleguide
- [ ] Remove all instances of AnyDuringMigration [beka/aaron]
- [x] Revert changes to the BlockDefinition type (in /blocks) https://github.com/google/blockly/issues/6248

Additional portions of the Blockly codebase (outside of `core/` to migrate:
- [x] `blocks/` and `generators/`: #6828
- [ ] `tests/` or portions thereof?
- [ ] `scripts/` or portions thereof?

**Comment by daniel-brenot** [comment]
I've been experimenting with this in my fork. I've deleted a large portion of the project structure for the moment and renamed all of the js files to ts. If you would like to work with me on this i am more than happy to accept help.

Most of the work i've been doing is using tools i'm making myself to do some simple find and replaces, although some syntax tree parsing seems to now be in order to handle things such converting the prototypes to classes, so that's my current focus. The branch i am currently on is mostly to see how far i can get with this and then once it is done i will create a new branch that i will squash the changes that are needed onto without having the messy history involved in the experimentation.

Feel free to contact me and check out my branch

**Comment by rachel-fenichel** [comment]
@daniel-brenot sure, can you send me a link to the relevant branch on your fork?

I've been working through the ES6 classes part: https://github.com/google/blockly/issues/5860 and associated pull requests. I've been using a tool to do the class conversions, then touching it up as needed. Some classes can't be converted yet, often because we're not calling `super` at the beginning of the constructor.

After class conversions the most critical thing is to get the build process working.

**Comment by daniel-brenot** [comment]
I'm looking into lebab for the automatic conversion. I'm experementing with multiple ways of doing most of the work automatically since the repository is so large.

My branch can be found here: https://github.com/daniel-brenot/blockly

**Comment by daniel-brenot** [comment]
Part of this is that it may be prudent to separate some of the work for blockly into separate repositories for things such as generators for different languages.

**Comment by rachel-fenichel** [comment]
Separate repositories, or just separate issues for tracking each piece of work?

The swap to Typescript tooling will not involve making separate repositories, because that expands the scope of the work well past a quarter.

In the future we want to move generators, block definitions, and some other files out of core and into plugins, but we need to have clear migration paths for developers and generally minimize disruption where possible.

**Comment by daniel-brenot** [comment]
Makes sense. In my local version i'm going to try to make typescript compile each one of the separate parts into a separate file with separate definitions to keep it compatible with how it seems to currently be done.

**Comment by BeksOmega** [comment]
I'm moving the task tracking here.

Pre merge:
- [x] Check all `@enums` for formatting issues. [beka] [mergable]
  - [x] Fix `KeyCodes` in `core/utils/keycodes.ts`. [christopher] [mergable]
- [x]  Check all `@typedef`s for lost JSDocs. [beka] [mergable]
- [x] Export `@typedef`s that were static properties on classes [beka] [mergable]
- [x] Move comments that migrants put in the wrong place [beka - optional] [mergable]
- [ ] Fix any `@protected` properties that have been changed to private parameter properties [TBD]
- [ ] Implement piping sourcemaps from tsc to closure compiler [christopher]
- [ ] Export interface types from `blockly.js/ts` [christopher]
- [ ] Deal with `IRegistrableField`? [TBD]

Post merge:
- [ ] Enable API Extractor. [maribeth]
- [ ] Migrate JSDoc to TSDoc. [TBD]
- [ ] Remove unused JSDoc attributes [optional]
- [ ] Figure out how to pipe the results of API Extractor to devsite [maribeth]

**Comment by daneongrand** [comment]
cool`console.log('cool')`

**Comment by BeksOmega** [comment]
I'm going to close this because it looks like we haven't been using it for task tracking in over a year.

**Comment by itsezc** [comment]
> I'm going to close this because it looks like we haven't been using it for task tracking in over a year.

Where is the tracking happening currently? Would love to stay up to date with the progress.
