### ISSUE TITLE
Where possible, convert to es6 classes.

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#5860]
Problematic classes (an incomplete list):

- [X] `generator.js` (Handled in #5928) 
  - Acts as both a [struct and a dict](https://github.com/google/closure-compiler/wiki/@struct-and-@dict-Annotations). We add properties after creation (like a dict) but also do . access (like a struct).
    - Can be fixed with the `@unrestricted` [annotation](https://github.com/google/closure-compiler/wiki/@struct-and-@dict-Annotations) on the class. --@rachel-fenichel 
  - Uses `Object.defineProperties` to add a property to the prototype.
- [X] `options.js`  (Handled in #5928)
  - Has a couple of functions (`setMetrics` and `getMetrics`) that don't always exist, but are declared for type purposes. Uses check whether these functions exist.
    - Declare these as data properties with `@type {function(....):... | undefined}`.  --@cpcallen
- [X] `shortcut_registry.js` (Handled in #5940)
  - Weird singleton pattern.
- [X] `contextmenu_registry.js` (Handled in #5940)
  - Weird singleton pattern.
- [X] `registry.js` (Handled in #5940)
- [X] `block_svg.js` (Handled in #5952)
  - Calls the super constructor late
- [X] `block.js` (Handled in #5952)
  - Has an unconverted subclass

### Toolbox
- [X] `toolbox/category.js` (Handled in #5947)
  - Has an unconverted subclass (`CollapsibleCategory`)
- [X] `toolbox/collapsible_category.js` (Handled in #5947)
  - I *think* the problem is that the superclass constructor uses the `registrationName` static property, which the subclass overrides. The property isn't overridden yet when the superclass constructor is called.
- [X] `toolbox/toolbox_item.js` (Handled in #5947)
  - Has an unconverted subclass (`ToolboxCategory`)

### Rendering:
- [X] `renderers/geras/path_object.js` (Handled in #5954)
  - Extends the base path object but doesn't call the super constructor. That's because the geras path object has to put a dark path in front of the main path, and z-index of svg objects is controlled by the order in which they are created.
- [X] `renderers/common/path_object.js` (Handled in #5954)
  - Has a non-converted subclass (see above)
- [X] `renderers/measurables/row.js` (Handled in #5957)
  - In code we add a few properties (`followsStatement`, `nextRightEdge`, and `rightAlignedDummyInput`) that don't really belong on this class. I could just add and describe them anyway, marked as package, if really necessary.
- [X] `renderers/measurables/base.js` (Handled in #5957)
  - Similar story to `measurables/row.js`

### Fields:
- [X] `field.js` (Handled in #5943)
  - Has multiple unconverted subclasses.
- [X] `field_textinput.js` (Handled in #5943)
  - Sets `this.spellcheck_ = true` before calling the super constructor, and breaks if the order changes.
- [X] `field_number.js` (Handled in #5943)
  - Sets multiple properties before calling the super constructor, and breaks if the order changes.
- [X] `field_image.js` (Handled in #5943)
  - Sets multiple properties before calling the super constructor, and breaks if the order changes.
- [X] `field_label.js (Handled in #5943)
- [X] `field_dropdown.js` (Handled in #5943)
- [X] `field_colour.js` (Handled in #5943)
- [X] `field_variable.js` (Handled in #5943)
- [X] `field_angle.js` (Handled in #5943)

### Events:
- [X] `events_abstract.js`  (Handled in #5928)
- [X] `workspace_events.js`  (Handled in #5928)
