### ISSUE TITLE
Additional type and cast cleanups

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#6097]
### Context

We enabled `strictMissingTypes` and `strictCheckProperties` in the closure build as a prerequisite for running MigranTS. Where possible we fixed type annotations properly, but in other places we need to do a refactor to make the types make sense--particularly where we tack properties onto SVG Elements to pass information around.

### Sub-issues
- [ ] `.tooltip` property on SVG Elements
- [ ] Touch/Gesture code uses `Event` and `PseudoEvent` instead of more specific types
  - [ ] `PointerEvents` are implemented on all of our supported browsers, so we can get rid of some of the touch code.
- [ ] `skew` and `translate` on SVG Elements in 

### See also
https://github.com/google/blockly/pull/6073
https://github.com/google/blockly/issues/5857
