### ISSUE TITLE
tracking bug: v11 breaking changes

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#7446]
This bug exists to track breaking changes that we intend to make in v11. Some of those require merging changes that we have ready but waiting.

- [x] https://github.com/google/blockly/issues/7226
- [x] https://github.com/google/blockly/issues/7245
- [x] https://github.com/google/blockly/issues/7068
- [x] Deprecate `render` https://github.com/google/blockly/pull/7355
- [x] Reroll https://github.com/google/blockly/pull/7364 and https://github.com/google/blockly/pull/7384 and verify https://github.com/google/blockly-samples/issues/1856
- [x] https://github.com/google/blockly/issues/6720
- [x] Add serialization hooks to procedure models
- [x] #7652 (due to likelihood of breaking TS users with custom block generator functions).
- [x] #7449 (due to wrapper cleanup and mooted changes to `package.json` to introduce `exports {}` section).
  - [x] #7822 
  - [x] #8091
- [x] Reroll https://github.com/google/blockly/pull/7694
- [x] #7665

**Comment by jogibear9988** [comment]
maybe this could also be fixed with V11? https://github.com/google/blockly/issues/1114
